# Generated by Django 3.1 on 2020-12-24 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mainboard',
            name='contents',
            field=models.TextField(verbose_name='CONTENTS'),
        ),
        migrations.AlterField(
            model_name='mainboard',
            name='title',
            field=models.CharField(max_length=50, verbose_name='TITLE'),
        ),
    ]
